//
//  DataTest.swift
//  CompanionApp5e
//
//  Created by Oreste Leone on 11/12/21.
//

import Foundation

var characterListData: [Character] = [
    Character(charName: "Elhein deRefiels",
              charClass: "Rogue",
              charRace: "High Elf",
              charLevel: 9,
              charClassArmor: 16,
              charHitPoints: 48,
              charInitiative: 5,
              charPP: 15,
              charSpeed: 30,
              charHPDice: 8,
              charProf: 4,
              charSTR: 12,
              charDEX: 20,
              charCON: 10,
              charINT: 12,
              charWIS: 12,
              charCHA: 14),
    
    Character(charName: "Davros Mehna",
              charClass: "Death Cleric",
              charRace: "Mountain Dwarf",
              charLevel: 5,
              charClassArmor: 14,
              charHitPoints: 43,
              charInitiative: 0,
              charPP: 13,
              charSpeed: 25,
              charHPDice: 8,
              charProf: 3,
              charSTR: 16,
              charDEX: 10,
              charCON: 16,
              charINT: 10,
              charWIS: 16,
              charCHA: 10),
    
    Character(charName: "Beledros del Clan Mereeth ra Ûthà",
              charClass: "Paladin",
              charRace: "Dragonborn",
              charLevel: 3,
              charClassArmor: 25,
              charHitPoints: 23,
              charInitiative: 3,
              charPP: 10,
              charSpeed: 25,
              charHPDice: 8,
              charProf: 2,
              charSTR: 18,
              charDEX: 12,
              charCON: 13,
              charINT: 10,
              charWIS: 10,
              charCHA: 18),

    Character(charName: "Anya",
              charClass: "Artificer",
              charRace: "Human",
              charLevel: 1,
              charClassArmor: 27,
              charHitPoints: 18,
              charInitiative: 5,
              charPP: 11,
              charSpeed: 30,
              charHPDice: 6,
              charProf: 2,
              charSTR: 10,
              charDEX: 18,
              charCON: 14,
              charINT: 18,
              charWIS: 12,
              charCHA: 12),

    Character(charName: "Alan",
              charClass: "Cleric",
              charRace: "Igniborne",
              charLevel: 3,
              charClassArmor: 36,
              charHitPoints: 56,
              charInitiative: 10,
              charPP: 14,
              charSpeed: 25,
              charHPDice: 10,
              charProf: 2,
              charSTR: 14,
              charDEX: 14,
              charCON: 16,
              charINT: 18,
              charWIS: 18,
              charCHA: 18)
]
